// Mocks generated by Mockito 5.4.6 from annotations
// in presentation/test/controllers/language_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:domain/user_preferences/entity/user_preferences.dart' as _i5;
import 'package:domain/user_preferences/use_case/get_user_preferences_usecase.dart'
    as _i2;
import 'package:domain/user_preferences/use_case/update_user_preferences.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [GetUserPreferencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserPreferencesUseCase extends _i1.Mock
    implements _i2.GetUserPreferencesUseCase {
  MockGetUserPreferencesUseCase() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [UpdateUserPreferencesUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserPreferencesUseCase extends _i1.Mock
    implements _i3.UpdateUserPreferencesUseCase {
  MockUpdateUserPreferencesUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> call(_i5.UserPreferences? preferences) =>
      (super.noSuchMethod(
            Invocation.method(#call, [preferences]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
