targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        enabled: true
        options:
          auto_register: true
          # Generates the config file for domain layer
          class_name_pattern: "^Domain"

